providers = ["php"]

[variables]
    PHP_VERSION = "8.2"
    NIXPACKS_NODE_VERSION = ""

[phases.install]
    cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
    cmd = "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
